---
title: "Showerhead Mycobacteria"
output: html_document
---

```{r data, message=FALSE, warning=FALSE}
ntm_relab <- read.delim("Gebert_SMP_Mapping_Plates1_7_COMPLETE_16S_FINAL_August2017_SampleEdit (1).txt", stringsAsFactors=FALSE)

ntm_relab$Latitude <- as.numeric(ntm_relab$Latitude)
ntm_relab$Longitude <- as.numeric(ntm_relab$Longitude)
ntm_relab$pH <- as.numeric(ntm_relab$pH)
ntm_relab$Total_Alkalinity <- as.numeric(ntm_relab$Total_Alkalinity)
ntm_relab$Total_Hardness <- as.numeric(ntm_relab$Total_Hardness)
ntm_relab$Free_Chlorine <- as.numeric(ntm_relab$Free_Chlorine)
ntm_relab$Total_Chlorine <- as.numeric(ntm_relab$Total_Chlorine)
ntm_relab$Nitrite <- as.numeric(ntm_relab$Nitrite)
ntm_relab$Nitrate <- as.numeric(ntm_relab$Nitrate)
ntm_relab$Total_Iron <- as.numeric(ntm_relab$Total_Iron)


```

```{r maps, message=FALSE}

library(maps)
library(tidyverse)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

usa <- map_data("usa")
states <- map_data("state")

ntm_contigusa <- ntm_relab%>%
  filter(Latitude> 24 & Latitude <50 & 
           Longitude > -130)

## USA Map

ggplot(data=ntm_contigusa, aes(Longitude, Latitude)) +
  geom_point(color=cbPalette[3], alpha=0.6) +
  geom_polygon(data = usa, aes(x=long, y = lat, group = group), 
               fill = cbPalette[1], color = cbPalette[2], alpha=0.2) + 
  coord_fixed(1.3) + theme_minimal() + 
  xlab("Longitude") +
  ylab("Latitude") + 
  ggtitle("Locations Sampled for NTM in Contiguous USA")


## USA Map with the State Outlines

ggplot(data=ntm_contigusa, aes(Longitude, Latitude)) +
  geom_point(color=cbPalette[3], alpha=0.6) +
  geom_polygon(data = states, aes(x=long, y = lat, group = group), 
               fill = cbPalette[1], color = cbPalette[2], alpha=0.2) + 
  coord_fixed(1.3) + theme_minimal() + 
  xlab("Longitude") +
  ylab("Latitude") + 
  ggtitle("Locations Sampled for NTM in Contiguous USA")


## USA Map with relative abundance

ggplot(data=ntm_contigusa, aes(Longitude, Latitude)) +
  geom_point(aes(color=Myco_Rel_Abund), alpha=1) +
  scale_color_viridis_c(option="inferno", direction = -1) + 
  geom_polygon(data = usa, aes(x=long, y = lat, group = group), 
               fill = cbPalette[1], alpha=0.1) + 
  coord_fixed(1.3) + theme_minimal() + 
  xlab("Longitude") +
  ylab("Latitude") + 
  ggtitle("Relative Abundance of NTM in Contiguous USA") 



```

```{r message=FALSE}

## values go between 0 and 100 

ntm_contigusa%>%
  ggplot(aes(Myco_Rel_Abund)) + 
  geom_histogram(fill=cbPalette[4], alpha=0.7, color="black") +
  theme_minimal()

```


There are `r sum(ntm_contigusa$Myco_Rel_Abund==0)` zero counts for NTM out of `r dim(ntm_contigusa)[1]` total observations. 


```{r}

# Visualizing the covariates in the data set

ntm_cusa_long <- ntm_contigusa%>%
  gather(covariates, value, -Myco_Rel_Abund, -Latitude, -Longitude, -X.SampleID, -Seq_Run, 
         -Source.of.Household.Water, -Showerhead.Installation.Time.Frame,
         -Frequency.of.Household.Shower.Usage, -Frequency.of.Showerhead.Cleaning, 
         -Showerhead.Cleaning.Solution, -Showerhead.Material, -Interior.Showerhead.Finish, 
         -Showerhead.System.Setup, -Does.the.Showerhead.Have.a.Filter., 
         -Showerhead.Spray.Pattern.Description, -How.is.Water.Heated, -Age.of.Hot.Water.Heater,
         -Hot.Water.Heater.Flush.Frequency, -Description)
   
ntm_cusa_long%>%
  ggplot(aes(value)) + 
  geom_histogram(aes(fill=covariates), color="black", alpha = 0.7) + 
  facet_wrap(~covariates, scales="free") +
  theme_minimal() +
  scale_fill_manual(values=cbPalette)
  

ntm_cusa_long%>%
  ggplot(aes(value, Myco_Rel_Abund)) + 
  geom_point(aes(color=covariates), alpha = 0.2) + 
  facet_wrap(~covariates, scales="free") +
  theme_minimal() + 
  scale_colour_manual(values=cbPalette)


```















